[package]
name = "readyset-server"
version = "0.7.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

readme = "README.md"
description = "The ReadySet data-flow database server"

keywords = ["database", "dataflow", "backend", "storage", "sql"]
categories = ["database", "database-implementations"]

[features]
default = []
generate_mysql_tests = ["default"]
profiling = ["timekeeper/default"]
bench = ["dataflow/bench"]
failure_injection = ["fail/failpoints", "readyset-client/failure_injection", "dataflow/failure_injection", "replicators/failure_injection"]
# Redact the display of strings marked sensitive from logs and error messages
redact_sensitive = ["readyset-util/redact_sensitive"]


[dependencies]
clap = { workspace = true, features = ["derive","env"] }
anyhow = { workspace = true }
bimap = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
ahash = { workspace = true }
futures = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
futures-sink = { workspace = true }
futures-executor = { workspace = true }
pin-project = { workspace = true }
hyper = { workspace = true, features = ["stream", "server"] }
querystring = { workspace = true }
itertools = { workspace = true }
metrics = { workspace = true }
metrics-util = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
nom = { workspace = true }
petgraph = { workspace = true, features = ["serde-1"] }
rand = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
slab = { workspace = true }
bincode = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-bincode = { workspace = true }
tracing = { workspace = true, features = ["release_max_level_debug"] }
vec1 = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true, features = ["serde"] }
tokio-stream = { workspace = true }
tokio-retry = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
tracing-futures = { workspace = true }
parking_lot = { workspace = true }
scopeguard = { workspace = true }
fail = { workspace = true }
sha1 = { workspace = true }
derive_more = { workspace = true }
streaming-iterator = { workspace = true }
proptest = { workspace = true }
once_cell = { workspace = true }
enum-kinds = { workspace = true }
slotmap = { workspace = true }
tikv-jemalloc-ctl = { workspace = true }
rlimit = { workspace = true }

timekeeper = { workspace = true }
vec_map = { workspace = true, features = ["eders"] }
serde = { workspace = true, features = ["rc", "derive"] }
tokio-tower = { workspace = true }
tower = { workspace = true, features = ["util"] }
strawpoll = { workspace = true }

# local deps
dataflow = { path = "../readyset-dataflow", package = "readyset-dataflow" }
dataflow-state = { path = "../dataflow-state" }
mir = { path = "../readyset-mir", package = "readyset-mir" }
common = { path = "../readyset-common", package = "readyset-common" }
readyset-alloc = { path = "../readyset-alloc" }
readyset-alloc-metrics = { path = "../readyset-alloc-metrics" }
readyset-client = { path = "../readyset-client" }
failpoint-macros = { path = "../failpoint-macros" }
readyset-errors = { path = "../readyset-errors" }
readyset-data = { path = "../readyset-data" }
readyset-util = { path = "../readyset-util" }
replicators = { path = "../replicators" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
array2 = { path = "../array2" }
nom-sql = { path = "../nom-sql" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter" }
readyset-version = { path = "../readyset-version" }
health-reporter = { path = "../health-reporter" }
database-utils = { path = "../database-utils" }
catalog-tables = { path = "../catalog-tables" }
replication-offset = { path = "../replication-offset" }
num_cpus = { workspace = true }

[dev-dependencies]
dataflow = { path = "../readyset-dataflow", package = "readyset-dataflow", features = ["bench"] }
test-utils = { path = "../test-utils" }
# Exact version dep here is only to avoid duplicate versions of downstream
# dependencies
backtrace = { workspace = true, features = ["serialize-serde"] }
toml = { workspace = true }
diff = { workspace = true }
tempfile = { workspace = true }
mysql = { workspace = true }
chrono = { workspace = true }
assert_approx_eq = { workspace = true }
assert_unordered = { workspace = true }
criterion = { workspace = true }
include_dir = { workspace = true }
rusty-fork = { workspace = true }
test-strategy = { workspace = true }
rust_decimal = { workspace = true }
triomphe = { workspace = true }

[[bench]]
name = "dataflow"
harness = false
