[package]
name = "readyset-server"
version = "0.7.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

readme = "README.md"
description = "The Readyset data-flow database server"

keywords = ["database", "dataflow", "backend", "storage", "sql"]
categories = ["database", "database-implementations"]

[features]
default = []
generate_mysql_tests = ["default"]
profiling = ["timekeeper/default"]
bench = ["dataflow/bench"]
failure_injection = [
    "fail/failpoints",
    "dataflow/failure_injection",
    "dataflow-state/failure_injection",
    "readyset-util/failure_injection",
    "schema-catalog/failure_injection",
    "replicators/failure_injection",
]
# Redact the display of strings marked sensitive from logs and error messages
redact_sensitive = ["readyset-util/redact_sensitive"]


[dependencies]
anyhow = { workspace = true }
antithesis_sdk = { workspace = true }
async-bincode = { workspace = true }
base64 = { workspace = true }
bimap = { workspace = true, features = ["serde"] }
bincode = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
enum-kinds = { workspace = true }
fail = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
hyper = { workspace = true, features = ["stream", "server", "http1"] }
indexmap = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
metrics-util = { workspace = true }
parking_lot = { workspace = true }
petgraph = { workspace = true, features = ["serde-1"] }
pin-project = { workspace = true }
quanta = { workspace = true }
querystring = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["rc", "derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }
sha1 = { workspace = true }
slotmap = { workspace = true }
strawpoll = { workspace = true }
streaming-iterator = { workspace = true }
tikv-jemalloc-ctl = { workspace = true }
timekeeper = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-retry = { workspace = true }
tokio-stream = { workspace = true }
tokio-tower = { workspace = true }
tower = { workspace = true, features = ["util"] }
tracing = { workspace = true, features = ["release_max_level_debug"] }
tracing-futures = { workspace = true }
url = { workspace = true, features = ["serde"] }
vec1 = { workspace = true }

# local deps
array2 = { path = "../array2" }
catalog-tables = { path = "../catalog-tables" }
common = { path = "../readyset-common", package = "readyset-common" }
database-utils = { path = "../database-utils" }
dataflow = { path = "../readyset-dataflow", package = "readyset-dataflow" }
dataflow-expression = { path = "../dataflow-expression" }
dataflow-state = { path = "../dataflow-state" }
failpoint-macros = { path = "../failpoint-macros" }
health-reporter = { path = "../health-reporter" }
mir = { path = "../readyset-mir", package = "readyset-mir" }
readyset-alloc = { path = "../readyset-alloc" }
readyset-alloc-metrics = { path = "../readyset-alloc-metrics" }
readyset-client = { path = "../readyset-client" }
readyset-data = { path = "../readyset-data" }
readyset-errors = { path = "../readyset-errors" }
readyset-sql = { path = "../readyset-sql" }
readyset-sql-parsing = { path = "../readyset-sql-parsing" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-util = { path = "../readyset-util" }
readyset-version = { path = "../readyset-version" }
replication-offset = { path = "../replication-offset" }
replicators = { path = "../replicators" }
schema-catalog = { path = "../schema-catalog" }

[dev-dependencies]
assert_approx_eq = { workspace = true }
assert_matches = { workspace = true }
chrono = { workspace = true }
criterion = { workspace = true }
dataflow = { path = "../readyset-dataflow", package = "readyset-dataflow", features = [
    "bench",
] }
diff = { workspace = true }
include_dir = { workspace = true }
mysql_async = { workspace = true }
readyset-decimal = { path = "../readyset-decimal" }
rusty-fork = { workspace = true }
tempfile = { workspace = true }
test-strategy = { workspace = true }
test-utils = { path = "../test-utils" }
triomphe = { workspace = true }

[[bench]]
name = "dataflow"
harness = false

[lints]
workspace = true
