[package]
name = "readyset-sql-parsing"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
itertools = { workspace = true }
nom-sql = { path = "../nom-sql" }
pretty_assertions = { workspace = true }
readyset-sql = { path = "../readyset-sql" }
sqlparser = { workspace = true, optional = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
sqlparser = ["dep:sqlparser"]
