[package]
name = "failpoint-proc-macros"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
syn = { workspace = true, features = ["full", "fold"] }
quote = { workspace = true }

[lib]
proc-macro = true
