[package]
name = "readyset-e2e-tests"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dev-dependencies]
chrono = { workspace = true }
dataflow-state = { path = "../dataflow-state" }
futures = { workspace = true }
itertools = { workspace = true }
mysql_async = { workspace = true }
mysql_common = { workspace = true }
paste = { workspace = true }
postgres-types = { workspace = true }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
readyset-adapter = { path = "../readyset-adapter" }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-client-test-helpers = { path = "../readyset-client-test-helpers" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-sql = { path = "../readyset-sql" }
readyset-sql-parsing = { path = "../readyset-sql-parsing" }
readyset-util = { path = "../readyset-util" }
schema-catalog = { path = "../schema-catalog" }
test-strategy = { workspace = true }
test-utils = { path = "../test-utils" }
tokio = { workspace = true, features = ["full"] }
tokio-postgres = { workspace = true }
fail = { workspace = true }

[features]
utf8mb4_all_codepoints_test = []
# Tests that rely on failpoints to inject schema catalog races.
failure_injection = [
    "fail/failpoints",
    "readyset-adapter/failure_injection",
    "readyset-util/failure_injection",
    "schema-catalog/failure_injection",
]

[lints.clippy]
dbg_macro = "warn"
# In a test crate, we are ok with todo!(); could remove them and just use workspace lints
todo = "allow"
