[package]
name = "readyset-logictest"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
antithesis_sdk = { workspace = true }
anyhow = { workspace = true }
bit-vec = { workspace = true, features = ["serde"] }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
console = { workspace = true }
derive_more = { workspace = true }
enum-display-derive = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
md5 = { workspace = true }
mysql_async = { workspace = true }
mysql_common = { workspace = true, features = ["chrono"] }
nom = { workspace = true }
nom_locate = { workspace = true }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-postgres = { workspace = true, features = ["with-chrono-0_4"] }
tracing = { workspace = true }
walkdir = { workspace = true }

database-utils = { path = "../database-utils" }
mysql-srv = { path = "../mysql-srv", optional = true }
mysql-time = { path = "../mysql-time" }
nom-sql = { path = "../nom-sql" }
psql-srv = { path = "../psql-srv", optional = true }
query-generator = { path = "../query-generator" }
readyset-adapter = { path = "../readyset-adapter", optional = true }
readyset-alloc = { path = "../readyset-alloc" }
readyset-client = { path = "../readyset-client", optional = true }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-data = { path = "../readyset-data" }
readyset-decimal = { path = "../readyset-decimal" }
readyset-mysql = { path = "../readyset-mysql", optional = true }
readyset-psql = { path = "../readyset-psql", optional = true }
readyset-server = { path = "../readyset-server/", optional = true }
readyset-shallow = { path = "../readyset-shallow", optional = true }
readyset-sql = { path = "../readyset-sql" }
readyset-sql-parsing = { path = "../readyset-sql-parsing" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-util = { path = "../readyset-util" }
schema-catalog = { path = "../schema-catalog" }

[features]
default = ["in-process-readyset"]
in-process-readyset = [
    "mysql-srv",
    "psql-srv",
    "readyset-adapter",
    "readyset-client",
    "readyset-mysql",
    "readyset-psql",
    "readyset-server",
    "readyset-shallow",
]

[lints.clippy]
dbg_macro = "warn"
# In a test crate, we are ok with todo!(); could remove them and just use workspace lints
todo = "allow"
