[package]
name = "readyset-logictest"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
anyhow = "1.0.38"
clap = { version = "3.0", features = ["derive","env"] }
console = "0.15.0"
derive_more = "0.99.11"
hex = "0.4.3"
md5 = "0.7.0"
mysql_async = { workspace = true }
mysql_common = { version = "0.28.0", features = ["chrono"] }
tikv-jemallocator = "0.4"
tokio-postgres = { workspace = true, features = ["with-chrono-0_4"] }
postgres-native-tls = { workspace = true }
native-tls = "0.2.7"
nom = "7.1"
nom_locate = "4.0.0"
tokio = { workspace = true, features = ["full"] }
itertools = "0.10.0"
chrono = "0.4.19"
pretty_assertions = "0.7.2"
walkdir = "2.3.2"
proptest = "1.0.0"
futures = "0.3"
tempfile = "3.4"
bytes = "1.0.1"
enum-display-derive = "0.1.1"
lazy_static = "1.4.0"
humantime = "2.1"
rust_decimal = { version = "1.26", features = ["db-tokio-postgres"] }
indicatif = "0.16"
bit-vec = { version = "0.6", features = ["serde"] }
thiserror = "1.0.30"

readyset-server = { path = "../readyset-server/" }
readyset-adapter = { path = "../readyset-adapter/" }
readyset-client = { path = "../readyset-client/" }
database-utils = { path = "../database-utils" }
nom-sql = { path = "../nom-sql" }
mysql-srv = { path = "../mysql-srv" }
psql-srv = { path = "../psql-srv" }
readyset-mysql = { path = "../readyset-mysql" }
readyset-psql = { path = "../readyset-psql" }
query-generator = { path = "../query-generator" }
mysql-time = { path = "../mysql-time" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-data = { path = "../readyset-data" }
readyset-util = { path = "../readyset-util" }
