dist: trusty
language: rust
rust:
  - nightly-2019-07-19
cache: cargo
script:
  - cargo check --all --all-targets
  - cargo test --verbose --all
services:
  zookeeper
addons:
  apt:
    packages:
    - libhwloc-dev
    - zookeeperd
    - liblz4-dev
