[workspace]
members = [
    "msql-srv",
    "nom-sql",
    "noria-client",
    "noria-mysql",
    "noria/noria",
    "noria/server",
    "noria/applications",
    "noria/noria-logictest",
    "noria/timestamp_service",
    "psql-srv",
    "unbounded-interval-tree",
    "launchpad",
    "connectors/debezium_connector",
    "query_generator",
    "taster"
]
[profile.release]
debug=true

[patch.crates-io]
# https://github.com/tower-rs/tokio-tower/pull/6
# optional -- just a perf optimization
# comment this out if you want cargo doc to work!
tokio-tower = { git = "https://github.com/tower-rs/tokio-tower.git", branch = "no-box" }
