[patch.crates-io]
tokio-postgres = {  git = "https://github.com/readysettech/rust-postgres.git"}
eui48 = { git = "https://github.com/readysettech/eui48.git", branch = "master" }

[workspace]
members = [
    "array2",
    "benchmarks",
    "catalog-tables",
    "concrete-iter",
    "data-generator",
    "database-utils",
    "dataflow-expression",
    "dataflow-state",
    "failpoint-macros",
    "failpoint-macros/proc-macros",
    "health-reporter",
    "merging-interval-tree",
    "mysql-srv",
    "mysql-time",
    "nom-sql",
    "nom-sql-arbitrary",
    "partial-map",
    "psql-srv",
    "query-generator",
    "reader-map",
    "readyset",
    "readyset-adapter",
    "readyset-adapter-types",
    "readyset-alloc",
    "readyset-alloc-metrics",
    "readyset-client",
    "readyset-client-metrics",
    "readyset-client-test-helpers",
    "readyset-clustertest",
    "readyset-clustertest",
    "readyset-common",
    "readyset-data",
    "readyset-dataflow",
    "readyset-errors",
    "readyset-logictest",
    "readyset-mir",
    "readyset-mysql",
    "readyset-psql",
    "readyset-repl",
    "readyset-server",
    "readyset-sql-passes",
    "readyset-telemetry-reporter",
    "readyset-tools",
    "readyset-tracing",
    "readyset-util",
    "readyset-version",
    "replication-offset",
    "replicators",
    "proptest-stateful",
    "system-benchmarks",
    "tinylb",
    "test-utils",
    "timestamp-service",
    "tournament-kway"
]
resolver = "2"

[workspace.dependencies]
consulrs = { git = "https://github.com/readysettech/consulrs.git", branch = "allow-disabling-rustls-tls-2" }
eui48 = { git = "https://github.com/readysettech/eui48.git", branch = "master", default-features = false }
metrics = { git = "https://github.com/readysettech/metrics.git" }
metrics-exporter-prometheus = { git = "https://github.com/readysettech/metrics.git" }
metrics-util = { git = "https://github.com/readysettech/metrics.git" }
mysql_async = { git = "https://github.com/readysettech/mysql_async" }
nperf-core = { git = "https://github.com/readysettech/not-perf.git" }
postgres = { git = "https://github.com/readysettech/rust-postgres.git" }
postgres-native-tls = { git = "https://github.com/readysettech/rust-postgres.git" }
postgres-protocol = { git = "https://github.com/readysettech/rust-postgres.git" }
postgres-types = { git = "https://github.com/readysettech/rust-postgres.git" }
rocksdb = { git = "https://github.com/readysettech/rust-rocksdb.git", default-features = false, features = ["lz4", "jemalloc"] }
tokio-postgres = { git = "https://github.com/readysettech/rust-postgres.git" }

ahash = "0.7"
anyhow = "1.0.42"
assert_approx_eq = "1.1.0"
assert_unordered = "0.3"
async-bincode = "0.6.1"
async-stream = "0.3.2"
async-trait = "0.1"
atomic-counter = "1.0.1"
backoff = "0.4.0"
backtrace = "=0.3.65"
bimap = "0.6.3"
bincode = "1.3.3"
bit-vec = "0.6"
blake2 = "0.10"
bufstream = "0.1.3"
byteorder = "1.0.0"
bytes = "1.0.1"
chrono = "0.4.19"
chrono-tz = "0.8.6"
cidr = "0.2.1"
clap = "4.3"
cloudflare-zlib = "0.2.9"
console = "0.15.5"
const-str = "0.5"
criterion = "0.5"
crossbeam-skiplist = "0.1.1"
csv = "1.2"
dashmap = "4.0.2"
deadpool-postgres = "0.10.3"
derive_builder = "0.11.2"
derive_more = "0.99.17"
diff = "0.1.10"
enum-display-derive = "0.1.1"
enum-kinds = "0.5.1"
enum_dispatch = "0.3.7"
envy = "0.4"
fail = "0.5.0"
fallible-iterator = "0.2.0"
fixedbitset = { version = "0.2.0", default-features = false }
fork = "0.1"
futures = "0.3.21"
futures-core = "0.3.14"
futures-executor = "0.3.14"
futures-sink = "0.3.14"
futures-util = "0.3.14"
fxhash = "0.2.1"
getrandom = "0.2.2"
growable-bloom-filter = "2.0.1"
hashbag = "0.1.2"
hdrhistogram = "7.4"
hex = "0.4.3"
hmac = "0.12.1"
humantime = "2.1"
hyper = "0.14.10"
include_dir = "0.6.2"
indexmap = { version = "1.9.2", default-features = false }
indicatif = "0.17"
indoc = "1.0.3"
iter-enum = "1.1.1"
itertools = "0.10.4"
lazy_static = "1.4.0"
left-right = "0.11"
libc = "0.2"
lru = "0.12.0"
machine-uid = "0.2"
md5 = "0.7.0"
mysql = "25"
mysql_common = "0.32"
native-tls = "0.2.8"
ndarray = "0.15.4"
nom = "7.1.1"
nom_locate = "4.0.0"
notify = "6.1.1"
num-integer = "0.1.44"
num_cpus = "1.16.0"
once_cell = "1.14"
opentelemetry = "0.21.0"
opentelemetry-otlp = "0.14.0"
opentelemetry-semantic-conventions = "0.13"
opentelemetry_sdk = "0.21.2"
paste = "1.0.5"
petgraph = "0.5"
pin-project = "1.0"
pprof = "0.13"
pratt = "0.3.0"
pretty_assertions = "1.4.0"
prettytable = "0.10.0"
proc-macro2 = "1"
prometheus-parse = "0.2.2"
proptest = "1.0.0"
quanta = { version = "0.11", default-features = false }
querystring = "1.1.0"
quickcheck = "0.9"
quickcheck_macros = "0.9"
quote = "1.0.8"
rand_distr = "0.4"
rand_regex = "0.15.1"
redis = "0.23.3"
regex = "1.8.4"
reqwest = "0.11.20"
rlimit = "0.10.1"
rmp-serde = "1.1.2"
rust_decimal = "1.26"
rusty-fork = "0.3.0"
rustyline = "11.0"
rustyline-derive = "0.6.0"
scopeguard = "1.1.0"
serde = "1.0.137"
serde_bytes = "0.11"
serde_derive = "1.0.8"
serde_json = "1.0.89"
serde_stacker = "0.1.7"
serde_with = "1.12"
serde_with_macros = "2.0.0"
serde_yaml = "0.8"
serial_test = "0.5.1"
sha-1 = "0.10.0"
sha1 = "0.10"
sha2 = "0.10.6"
slab = "0.4.2"
slotmap = "1.0.6"
smallvec = { version = "1.9.0", default-features = false }
socket2 = "0.4"
sqlformat = "0.2.1"
sqlparser = "0.41.0"
strawpoll = "0.2.2"
streaming-iterator = "0.1"
stringprep = "0.1.2"
structopt = "0.2"
strum = "0.23"
strum_macros = "0.23"
syn = { version = "1.0.57", default-features = false }
temp-dir = "0.1"
tempfile = "3.8.1"
test-strategy = "0.2.0"
textwrap = "0.14"
thiserror = "1.0.31"
tikv-jemalloc-ctl = "0.5.0"
tikv-jemalloc-sys = "0.5.0"
tikv-jemallocator = "0.5.0"
time = "0.3"
timekeeper = { version = "0.3.2", default-features = false }
tokio = { version = "1.32",  features = ["full"] }
tokio-native-tls = "0.3.1"
tokio-retry = "0.3"
tokio-scoped = "0.2.0"
tokio-stream = "0.1.5"
tokio-test = "0.4.3"
tokio-tower = "0.5.1"
tokio-util = "0.6.6"
toml = "0.5"
tower = "0.4.6"
tower-layer = "0.3.1"
tower-service = "0.3.1"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-attributes = "0.1.27"
tracing-futures = "0.2.5"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = "0.3.9"
triomphe = "0.1"
tuple = "0.5.1"
url = "2.2.2"
uuid = "0.8"
vec1 = "1.8.0"
vec_map = "0.8.0"
vmemcached = "0.5.0"
walkdir = "2.3.2"
zipf = "7.0.0"

[profile.release]
debug=true

[profile.release-dist]
# configs for distro release packages (i.e. deb, rpm, etc.)
inherits = "release"
debug = false
strip = "debuginfo"
