[package]
name = "unbounded-interval-tree"
version = "0.2.1"
authors = ["Jonathan Guillotte-Blouin <jonathan.guillotte.blouin@gmail.com>"]
edition = "2018"
license = "MIT"
description = "An interval tree working with inclusive/exclusive bounds, as well as unbounded intervals. Provides helpers to fetch overlapping intervals, and difference of intervals."

repository = "https://github.com/jonathanGB/unbounded-interval-tree"
keywords = ["interval", "tree", "bound", "exclusive", "difference"]

[dependencies]
rand = "0.7"