[patch.crates-io]
tokio-postgres = {  git = "https://github.com/readysettech/rust-postgres.git"}
eui48 = { git = "https://github.com/readysettech/eui48.git", branch = "master" }
opentelemetry = { git = "https://github.com/open-telemetry/opentelemetry-rust" }
opentelemetry-otlp = { git = "https://github.com/open-telemetry/opentelemetry-rust" }
opentelemetry-semantic-conventions = { git = "https://github.com/open-telemetry/opentelemetry-rust" }

[workspace]
members = [
    "array2",
    "benchmarks",
    "catalog-tables",
    "concrete-iter",
    "data-generator",
    "database-utils",
    "dataflow-expression",
    "dataflow-state",
    "failpoint-macros",
    "failpoint-macros/proc-macros",
    "health-reporter",
    "merging-interval-tree",
    "mysql-srv",
    "mysql-time",
    "nom-sql",
    "nom-sql-arbitrary",
    "partial-map",
    "psql-srv",
    "query-generator",
    "reader-map",
    "readyset",
    "readyset-adapter",
    "readyset-alloc",
    "readyset-client",
    "readyset-client-metrics",
    "readyset-client-test-helpers",
    "readyset-clustertest",
    "readyset-clustertest",
    "readyset-common",
    "readyset-data",
    "readyset-dataflow",
    "readyset-errors",
    "readyset-logictest",
    "readyset-mir",
    "readyset-mysql",
    "readyset-psql",
    "readyset-repl",
    "readyset-server",
    "readyset-sql-passes",
    "readyset-telemetry-reporter",
    "readyset-tools",
    "readyset-tracing",
    "readyset-util",
    "readyset-version",
    "replicators",
    "proptest-stateful",
    "system-benchmarks",
    "test-utils",
    "timestamp-service",
    "tournament-kway"
]
resolver = "2"

[workspace.dependencies]
clap = "4.3"
consulrs = { git = "https://github.com/readysettech/consulrs.git", branch = "allow-disabling-rustls-tls-2" }
eui48 = { git = "https://github.com/readysettech/eui48.git", branch = "master", default-features = false }
mysql_async = { git = "https://github.com/readysettech/mysql_async" }
nperf-core = { git = "https://github.com/readysettech/not-perf.git" }
postgres = {  git = "https://github.com/readysettech/rust-postgres.git"}
postgres-native-tls = {  git = "https://github.com/readysettech/rust-postgres.git"}
postgres-protocol = {  git = "https://github.com/readysettech/rust-postgres.git"}
postgres-types = {  git = "https://github.com/readysettech/rust-postgres.git"}
tokio-postgres = {  git = "https://github.com/readysettech/rust-postgres.git"}
tokio = { version = "1.28",  features = ["full"] }
rocksdb = { git = "https://github.com/readysettech/rust-rocksdb.git", default-features = false, features = ["lz4"] }

[profile.release]
debug=true
