[package]
name = "readyset-adapter"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive","env"] }
fail = { workspace = true }
futures-executor = { workspace = true }
futures-util = { workspace = true }
lazy_static = { workspace = true }
nom-sql = { path = "../nom-sql" }
nom = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true, features = ["full"] }
chrono = { workspace = true }
tracing = { workspace = true, features = ["release_max_level_debug"] }
tracing-futures = { workspace = true }
vec1 = { workspace = true }
itertools = { workspace = true }
derive_more = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
readyset-util = { path = "../readyset-util" }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
metrics-util = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rust_decimal = { workspace = true }
bit-vec = { workspace = true, features = ["serde"] }
hyper = { workspace = true, features = ["stream", "server"] }
tokio-stream = { workspace = true, features = ["net"] }
tokio-tower = { workspace = true }
tower = { workspace = true, features = ["util"] }
time = { workspace = true, features = ["local-offset"] }
dashmap = { workspace = true }
mysql_common = { workspace = true }
bincode = { workspace = true }
parking_lot = { workspace = true }
sqlformat = { workspace = true }
indexmap = { workspace = true }
quanta = { workspace = true }
lru = { workspace = true }
crossbeam-skiplist = { workspace = true }
slab = { workspace = true }

readyset-adapter-types = { path = "../readyset-adapter-types/" }
readyset-alloc = { path = "../readyset-alloc/" }
readyset-client = { path = "../readyset-client/" }
readyset-errors = { path = "../readyset-errors/" }
readyset-data = { path = "../readyset-data/" }
readyset-server = { path = "../readyset-server" }
timestamp-service = {path= "../timestamp-service/"}
dataflow-expression = { path = "../dataflow-expression" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-version = { path = "../readyset-version" }
health-reporter = { path = "../health-reporter" }
database-utils = { path = "../database-utils" }

[dev-dependencies]
proptest = { workspace = true }
test-strategy = { workspace = true }
criterion = { workspace = true } 
rand = { workspace = true }

[lib]
path = "src/lib.rs"

[[bench]]
name = "parse"
harness = false

[features]
ryw = []
failure_injection = ["fail/failpoints"]
