[package]
name = "readyset-version"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const-str = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
