[package]
name = "readyset-common"
version = "0.7.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

description = "Artifacts commonly shared among other Readyset crates"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["rc", "derive"] }
petgraph = { workspace = true, features = ["serde-1"] }
proptest = { workspace = true }
test-strategy = { workspace = true }
rlimit = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true }
bincode = { workspace = true }
metrics = { workspace = true }

# Local deps
readyset-client = { path = "../readyset-client" }
readyset-data = { path = "../readyset-data" }
readyset-errors = { path = "../readyset-errors" }
readyset-util = { path = "../readyset-util" }

[lints]
workspace = true
