[package]
name = "readyset-common"
version = "0.7.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

description = "Artifacts commonly shared among other ReadySet crates"

[dependencies]
chrono = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0.8", features = ["rc", "derive"] }
petgraph = { version = "0.5", features = ["serde-1"] }
vec1 = "1.6.0"
tuple = "0.5"
triomphe = "0.1"
proptest = "1.0"
test-strategy = "0.2.0"

# Local deps
readyset-client = { path = "../readyset-client" }
readyset-data = { path = "../readyset-data" }
readyset-util = { path = "../readyset-util" }
