[package]
name = "readyset-clustertest"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
futures-util = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
url = { workspace = true }
mysql_async = { workspace = true }
tokio-postgres = { workspace = true }
envy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
hyper = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true, features = ["release_max_level_debug"] }

# local deps
database-utils = { path = "../database-utils" }
nom-sql = { path = "../nom-sql" }
readyset-adapter = { path = "../readyset-adapter" }
readyset-client = { path = "../readyset-client", features = ["failure_injection"] }
readyset-data = { path = "../readyset-data" }
readyset-util = { path = "../readyset-util" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-errors = { path = "../readyset-errors" }

[dev-dependencies]
serial_test = { workspace = true }
criterion = { workspace = true, features=['real_blackbox', 'async_tokio']}
itertools = { workspace = true }
readyset-client-metrics = { path = "../readyset-client-metrics" }
test-utils = { path = "../test-utils" }
readyset-clustertest-macros = { path = "./macros" }
readyset-tracing = { path = "../readyset-tracing" }
rust_decimal = { workspace = true }

[[bench]]
name = "clustering"
harness = false

[features]
slow_bench = []
failure_injection = ["readyset-client/failure_injection"]
