[package]
name = "readyset-clustertest"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
url = { workspace = true }
mysql_async = { workspace = true }
tokio-postgres = { workspace = true }
envy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
hyper = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true, features = ["release_max_level_debug"] }

# local deps
database-utils = { path = "../database-utils" }
readyset-adapter = { path = "../readyset-adapter" }
readyset-client = { path = "../readyset-client" }
readyset-data = { path = "../readyset-data" }
readyset-decimal = { path = "../readyset-decimal" }
readyset-sql = { path = "../readyset-sql" }
readyset-sql-parsing = { path = "../readyset-sql-parsing" }
readyset-util = { path = "../readyset-util", features = ["failure_injection"] }
readyset-tracing = { path = "../readyset-tracing" }
readyset-errors = { path = "../readyset-errors" }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
itertools = { workspace = true }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-clustertest-macros = { path = "./macros" }
readyset-tracing = { path = "../readyset-tracing" }
test-utils = { path = "../test-utils" }

[build-dependencies]
anyhow = { workspace = true }
jobserver = { workspace = true }

[[bench]]
name = "clustering"
harness = false

[features]
slow_bench = []
failure_injection = ["readyset-util/failure_injection"]

[lints.clippy]
dbg_macro = "warn"
# In a test crate, we are ok with todo!(); could remove them and just use workspace lints
todo = "allow"
