[package]
name = "readyset-client"
version = "0.7.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

readme = "README.md"
description = "Client bindings for Readyset"

keywords = ["database", "dataflow", "backend", "storage", "sql"]
categories = ["api-bindings", "database"]

[dependencies]
anyhow = { workspace = true }
async-bincode = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
fail = { workspace = true }
hyper = { workspace = true, features = ["stream", "client", "http2", "tcp", "runtime"] }
serde = { workspace = true, features = ["rc", "derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
rmp-serde = { workspace = true }
tokio = { workspace = true, features = ["full"] }
bincode = { workspace = true }
vec_map = { workspace = true, features = ["eders"] }
petgraph = { workspace = true, features = ["serde-1"] }
ahash = { workspace = true }
tower-service = { workspace = true }
tokio-tower = { workspace = true }
tower = { workspace = true, features = [
    "limit",
    "balance",
    "buffer",
    "discover",
    "util",
    "timeout",
] }
tracing = { workspace = true, features = ["release_max_level_debug"] }
tracing-futures = { workspace = true }
slab = { workspace = true }
futures-util = { workspace = true }
futures = { workspace = true }
vec1 = { workspace = true, features = ["serde"] }
proptest = { workspace = true }
derive_more = { workspace = true }
url = { workspace = true, features = ["serde"] }
rand = { workspace = true }
parking_lot = { workspace = true }
smallvec = { workspace = true }
rocksdb.workspace = true
metrics = { workspace = true }
metrics-util = { workspace = true }
itertools = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
triomphe = { workspace = true }
streaming-iterator = { workspace = true }
test-strategy = { workspace = true }
deadpool = { workspace = true }

# consensus/
enum_dispatch = { workspace = true }
async-trait = { workspace = true }

# metrics/
reqwest = { workspace = true, features = ["json"] }

# Local dependencies
failpoint-macros = { path = "../failpoint-macros" }
readyset-sql = { path = "../readyset-sql" }
readyset-util = { path = "../readyset-util" }
readyset-errors = { path = "../readyset-errors" }
readyset-data = { path = "../readyset-data" }
dataflow-expression = { path = "../dataflow-expression" }
readyset-tracing = { path = "../readyset-tracing" }
array2 = { path = "../array2" }
tournament-kway = { path = "../tournament-kway" }
readyset-sql-parsing = { path = "../readyset-sql-parsing" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
replication-offset = { path = "../replication-offset" }

[dev-dependencies]
tempfile = { workspace = true }
test-utils = { path = "../test-utils" }

[features]
failure_injection = ["fail/failpoints"]

[lints]
workspace = true
