[package]
name = "readyset-shallow"
version = "0.0.1"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
dashmap = { workspace = true }
metrics = { workspace = true }
moka = { workspace = true }
papaya = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
mysql_async = { workspace = true }
mysql_common = { workspace = true }
tokio-postgres = { workspace = true }
psql-srv = { path = "../psql-srv" }

readyset-client = { path = "../readyset-client" }
readyset-errors = { path = "../readyset-errors" }
readyset-sql = { path = "../readyset-sql" }
readyset-util = { path = "../readyset-util" }

[dev-dependencies]
assert_matches = { workspace = true }
futures = { workspace = true }
proptest = { workspace = true }
