[package]
name = "catalog-tables"
version = "0.0.1"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
readyset-sql = { path = "../readyset-sql" }

[lints]
workspace = true
