[package]
name = "schema-catalog"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
antithesis_sdk = { workspace = true }
async-trait = { workspace = true }
readyset-errors = { path = "../readyset-errors" }
readyset-data = { path = "../readyset-data" }
readyset-sql = { path = "../readyset-sql" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-util = { path = "../readyset-util" }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
metrics = { workspace = true }
serde_json = { workspace = true }
failpoint-macros = { path = "../failpoint-macros" }
futures-util = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
fail = { workspace = true, optional = true }

[features]
failure_injection = ["readyset-util/failure_injection", "fail/failpoints", "fail"]

[lints]
workspace = true
