[package]
name = "readyset-data"
version = "0.0.1"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bit-vec = { workspace = true, features = ["serde"] }
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
eui48 = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
mysql_common = { workspace = true, features = ["chrono"] }
proptest = { workspace = true }
regex = { workspace = true }
rust_decimal = { workspace = true, features = ["db-tokio-postgres", "serde-str"] }
serde = { workspace = true, features = ["rc", "derive"] }
serde_bytes = { workspace = true }
serde_json = { workspace = true, features = ["arbitrary_precision", "unbounded_depth"] }
serde_stacker = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
test-strategy = { workspace = true }
time = { workspace = true, features = ["local-offset"] }
triomphe = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
enum-kinds = { workspace = true }
ndarray = { workspace = true, features = ["serde"] }
fallible-iterator = { workspace = true } # Only for internals of ToSql impls
nom = { workspace = true }
nom_locate = { workspace = true }
postgres-protocol = { workspace = true }
cidr = { workspace = true }
postgres-types = { workspace = true, features = ["with-cidr-0_2"] }
vec1 = { workspace = true }

# Local dependencies
nom-sql = { path = "../nom-sql" }
readyset-util = { path = "../readyset-util" }
readyset-errors = { path = "../readyset-errors" }
mysql-time = { path = "../mysql-time" }
smallvec = { workspace = true, features = ["union", "const_generics", "serde"] }

[dependencies.tokio-postgres]
workspace = true
features = ["with-chrono-0_4", "with-eui48-1", "with-uuid-0_8", "with-serde_json-1", "with-bit-vec-0_6"]

[dev-dependencies]
derive_more = { workspace = true }
bincode = { workspace = true }
criterion = { workspace = true, features=['real_blackbox', 'async_tokio']}
tokio = { workspace = true, features = ["full"] }
serial_test = { workspace = true }

[[bench]]
name = "serde"
harness = false
