name: readyset
services:
  cache:
    image: "docker.io/readysettech/readyset:latest"
    platform: linux/amd64
    ports:
      # The ReadySet Adapter listen port, i.e. what your application / SQL shell connects to
      - "5433:5433"
      # ReadySet Prometheus metrics available at http://localhost:6034/metrics
      # e.g. curl -X GET http://localhost:6034/metrics
      - "6034:6034"
    environment:
      DEPLOYMENT_ENV: quickstart_docker
      STORAGE_DIR: /state
      PROMETHEUS_METRICS: true
      QUERY_CACHING: explicit
      QUERY_LOG: true
      QUERY_LOG_AD_HOC: true
      STANDALONE: true
      DEPLOYMENT: docker_compose_deployment
      LISTEN_ADDRESS: 0.0.0.0:5433
      # UPSTREAM_DB_URL:
      CONTROLLER_ADDRESS: 0.0.0.0
    volumes:
      - "readyset:/state"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "127.0.0.1:6034/health" ]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 5s
  prometheus:
    image: "public.ecr.aws/readyset/readyset-prometheus:latest"
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9090"]
      interval: 5s
      timeout: 5s
      retries: 12
    expose:
      - 9090
    volumes:
      - "prometheus:/prometheus"
  pushgateway:
    image: prom/pushgateway
    expose:
      - 9091
  grafana:
    image: "public.ecr.aws/readyset/readyset-grafana:latest"
    ports:
      - 4000:4000
    environment:
      # UPSTREAM_DB_URL:
      RS_PORT: 5433
      RS_GRAFANA_PORT: 4000
volumes:
  prometheus: ~
  readyset: ~
