name: readyset
services:
  cache:
    image: "docker.io/readysettech/readyset:latest"
    platform: linux/amd64
    ports:
      # The ReadySet Adapter listen port, i.e. what your application / SQL shell connects to
      - "5433:5433"
      # ReadySet Prometheus metrics available at http://localhost:6034/metrics
      # e.g. curl -X GET http://localhost:6034/metrics
      - "6034:6034"
    environment:
      DEPLOYMENT_ENV: quickstart_docker
      STORAGE_DIR: /state
      PROMETHEUS_METRICS: true
      QUERY_CACHING: explicit
      QUERY_LOG_MODE: all-queries
      STANDALONE: true
      DEPLOYMENT: docker_compose_deployment
      LISTEN_ADDRESS: 0.0.0.0:5433
      # UPSTREAM_DB_URL:
      CONTROLLER_ADDRESS: 0.0.0.0
    volumes:
      - "readyset:/state"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "127.0.0.1:6034/health" ]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 5s
volumes:
  readyset: ~
