[package]
name = "readyset-util"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"
description = "Extensions to the Rust standard library"

[dependencies]
anyhow = "1.0"
proptest = "1.0.0"
chrono = { version = "0.4.0", features = ["serde"] }
tokio = { workspace = true, features = ["full"] }
futures = "0.3"
tracing = { version = "0.1", features = ["release_max_level_debug"] }
rust_decimal = { version = "1.26" }
eui48 = { workspace = true }
uuid = { version = "0.8", features = ["v4"] }
serde_json = "1"
bit-vec = { version = "0.6", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
async-stream = "0.3.2"
cidr = "0.2.1"

[dev-dependencies]
test-strategy = "0.2.0"

[features]
# Redact the display of strings marked sensitive from logs and error messages
redact_sensitive = []
