[package]
name = "readyset-util"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"
description = "Extensions to the Rust standard library"

[dependencies]
exponential-backoff = { workspace = true }
bytes = { workspace = true }
proptest = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
chrono-tz = { workspace = true }
fail = { workspace = true }
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true, features = ["release_max_level_debug"] }
rust_decimal = { workspace = true }
eui48 = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
serde_json = { workspace = true }
bit-vec = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
async-stream = { workspace = true }
cidr = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
test-strategy = { workspace = true }
test-utils = { path = "../test-utils" }
rand = { workspace = true }
pprof = { workspace = true, features = ["flamegraph", "criterion"] }
postgres = { workspace = true, features = [
    "with-chrono-0_4",
    "with-eui48-1",
    "with-uuid-0_8",
    "with-serde_json-1",
    "with-bit-vec-0_6",
] }

[features]
# Redact the display of strings marked sensitive from logs and error messages
redact_sensitive = []
failure_injection = ["fail/failpoints"]

[[bench]]
name = "fmt"
harness = false

[lints]
workspace = true
