[package]
name = "readyset-repl"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "wrap_help"] }
console = { workspace = true }
rustyline = { workspace = true }
rustyline-derive = { workspace = true }
tokio = { workspace = true, features = ["full"] }
prettytable = { workspace = true }
postgres-types = { workspace = true }
textwrap = { workspace = true }
nom = { workspace = true }

database-utils = { path = "../database-utils" }
readyset-data = { path = "../readyset-data" }

[lints]
workspace = true
