[package]
name = "readyset-repl"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { workspace = true, features = ["derive", "wrap_help"] }
console = "0.15.8"
rustyline = "12.0"
rustyline-derive = "0.10.0"
tokio = { workspace = true, features = ["full"] }
prettytable = "0.10.0"
postgres-types = { workspace = true }
textwrap = "0.16"
nom = "7.1.1"
hermit-abi = "0.3.3"

database-utils = { path = "../database-utils" }
readyset-data = { path = "../readyset-data" }
readyset-errors = { path = "../readyset-errors" }
