[package]
name = "dataflow_expression"
version = "0.1.0"
publish = false
authors = ["Griffin Smith <grfn@readyset.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.0", features = ["serde"] }
chrono-tz = { version = "0.5", features = ["serde"] }
serde = { version = "1.0.8", features = ["derive"] }
rust_decimal = { version = "1.16" }
lazy_static = "1.4.0"
regex = "1.4.3"

# Local deps
launchpad = { path = "../../../../launchpad" }
maths = { path = "../../../../maths" }
mysql-time = { path = "../../../../mysql-time" }
nom-sql = { path = "../../../../nom-sql" }
noria-data = { path = "../../../data" }
noria-errors = { path = "../../../errors" }

[dev-dependencies]
test-strategy = "0.2.0"
pretty_assertions = "0.7.2"
proptest = "1.0.0"
