[package]
name = "readyset-telemetry-reporter"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
backoff = { version = "0.4.0", features = ["tokio"] }
base64 = "0.13"
derive_builder = "0.11.2"
hex = "0.4"
lazy_static = "1.4"
reqwest = { version = "0.11.7", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with_macros = "2.0.0"
thiserror = "1.0"
tokio = { workspace = true, features = ["full"] }
tracing = { version = "0.1", features = ["release_max_level_debug"] }
readyset-tracing = { path = "../readyset-tracing" }
uuid = { version = "0.8", features = [ "v4" ] }
machine-uid = "0.2"
blake2= "0.10"

readyset-version = { path = "../readyset-version" }

[dev_dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }

[features]
test-util = []

