[package]
name = "readyset-telemetry-reporter"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = { workspace = true }
backoff = { workspace = true, features = ["tokio"] }
base64 = "0.13"
derive_builder = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with_macros = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["release_max_level_debug"] }
readyset-tracing = { path = "../readyset-tracing", optional = true }
readyset-util = { path = "../readyset-util" }
uuid = { workspace = true, features = ["v4"] }
machine-uid = { workspace = true }
blake2 = { workspace = true }

readyset-version = { path = "../readyset-version" }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }

[features]
test-util = ["readyset-tracing"]
