---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readyset-adapter
  namespace: {{ required "You must pass a namespace" (.Release.Namespace | quote) }}
  labels: {{ include "readyset.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  selector:
    matchLabels: {{ include "readyset.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "readyset.labels" . | nindent 8 }}
    spec:
      serviceAccountName: readyset-adapter
      containers:
        - name: consul-agent
          image: hashicorp/consul:1.15.2
          volumeMounts:
            - mountPath: /usr/src/app/entrypoint.sh
              name: init
              subPath: entrypoint.sh
          command: [
            "/bin/sh"
          ]
          args:
            - "/usr/src/app/entrypoint.sh"
          ports:
          - containerPort: 8500
            name: http
            protocol: TCP
          - containerPort: 8301
            name: serflan-tcp
            protocol: TCP
          - containerPort: 8301
            name: serflan-udp
            protocol: UDP
          - containerPort: 8600
            name: dns-tcp
            protocol: TCP
          - containerPort: 8600
            name: dns-udp
            protocol: UDP
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ADVERTISE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CONSUL_SERVER_NAMESPACE
              value: "{{ .Values.readyset.namespace | default .Release.Namespace }}"
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -ec
              - |
                curl http://127.0.0.1:8500/v1/health/node/$(hostname) \
                2>/dev/null | grep -E '".+"'
        - name: readyset-adapter
          image: {{ default (include "readyset.adapter.imageDefault" .) .Values.readyset.adapter.imageOverride }}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
          env:
            - name: LISTEN_ADDRESS
              value: 0.0.0.0:{{ .Values.readyset.adapter.port | default (include "readyset.mysqlPort" . ) }}
            # Database ReadySet is proxying to
            - name: UPSTREAM_DB_URL
              valueFrom:
                secretKeyRef:
                  name: readyset-upstream-database
                  key: url
            - name: LOG_FORMAT
              value: "json"
            - name: DEPLOYMENT
              value: "{{ required "readyset.deployment is a required value" .Values.readyset.deployment }}"
            # Identify this as a Helm deployment to TelemetryReporter
            - name: QUERY_CACHING
              value: {{ (include "readyset.queryCachingMode" .) | default "explicit" }}
            - name: DEPLOYMENT_ENV
              value: "helm"
            - name: AUTHORITY_ADDRESS
              value: "readyset-consul-server:8500"
            - name: AUTHORITY
              value: "consul"
            - name: METRICS_ADDRESS
              value: "0.0.0.0:{{ .Values.readyset.adapter.httpPort | default (include "readyset.adapter.httpPort" . ) }}"
            - name: PROMETHEUS_METRICS
              value: "true"
            - name: QUERY_LOG
              value: "true"
            - name: RUST_BACKTRACE
              value: "1"
            - name: VIEWS_POLLING_INTERVAL
              value: "180"
            {{- if .Values.readyset.adapter.queryLogAdHoc }}
            - name: QUERY_LOG_AD_HOC
              value: {{ .Values.readyset.adapter.queryLogAdHoc | quote }}
            {{- end }}
            {{- if .Values.readyset.adapter.statementLogging }}
            - name: STATEMENT_LOGGING
              value: {{ .Values.readyset.adapter.statementLogging | quote }}
            {{- end }}
          resources:
            requests:
              cpu: {{ default "500m" .Values.readyset.adapter.resources.requests.cpu }}
              memory: {{ default "1Gi" .Values.readyset.adapter.resources.requests.memory }}
          ports:
            - containerPort: {{ .Values.readyset.adapter.httpPort | default (include "readyset.adapter.httpPort" . ) }}
              name: monitoring
              protocol: TCP
            - containerPort: {{ .Values.readyset.adapter.port | default (include "readyset.mysqlPort" . ) }}
              name: {{ default "mysql" .Values.readyset.adapter.type}}
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -ec
              - |
                curl --fail http://127.0.0.1:{{ .Values.readyset.adapter.httpPort | default (include "readyset.adapter.httpPort" . ) }}/health
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -ec
              - |
                curl --fail http://127.0.0.1:{{ .Values.readyset.adapter.httpPort | default (include "readyset.adapter.httpPort" . ) }}/health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
      volumes:
        - configMap:
            items:
            - key: entrypoint.sh
              path: entrypoint.sh
            name: readyset-consul-agent-cm
          name: init
