[package]
name = "readyset-sql-passes"
version = "0.0.1"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
itertools = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
vec1 = { workspace = true }

# Local dependencies
readyset-errors = { path = "../readyset-errors" }
readyset-data = { path = "../readyset-data" }
readyset-sql = { path = "../readyset-sql" }
dataflow-expression = { path = "../dataflow-expression" }

[dev-dependencies]
criterion = { workspace = true }
pretty_assertions = { workspace = true }
readyset-sql-parsing = { path = "../readyset-sql-parsing" }

[[bench]]
name = "adapter_rewrites"
harness = false

[lints]
workspace = true
