[package]
name = "readyset-tools"
version = "0.1.0"
publish = false
authors = ["Readyset Technology, Inc. <info@readyset.io>"]
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
failpoint-client = { path = "../failpoint-client" }
serde_json = { workspace = true }
readyset-client = { path = "../readyset-client" }
tokio = { workspace = true, features = ["full"] }
readyset-server = { path = "../readyset-server" }

[[bin]]
name = "view_checker"
path = "src/view_checker.rs"

[[bin]]
name = "controller_request"
path = "src/controller_request.rs"

[[bin]]
name = "make_config_json"
path = "src/make_config_json.rs"

[[bin]]
name = "failpoint"
path = "src/failpoint.rs"

[lints]
workspace = true
