[package]
name = "readyset-alloc"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[features]
# Build jemalloc's profiling features. Without this
# certain profile functions will return nothing.
mem-profiling = ["tikv-jemallocator/profiling"]

[dependencies]
futures = { version = "0.3", features = ["executor", "thread-pool"]}
fxhash = "0.2.1"
lazy_static = "1.3"
libc = "0.2"
tikv-jemalloc-ctl = "0.5.0"
tikv-jemalloc-sys = { version = "0.5.0", features = ["stats"] }
tikv-jemallocator = { version = "0.5.0", features = ["unprefixed_malloc_on_supported_platforms", "stats"] }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
tempfile = "3.0"

