[package]
name = "nom-sql"
version = "0.0.11"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

homepage = "https://github.com/readysettech/readyset/tree/master/nom-sql"
repository = "https://github.com/readysettech/readyset/tree/master/nom-sql"

description = "A SQL parser written using nom."

[dependencies]
clap = { workspace = true, features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
nom = "7.1"
itertools = "0.10"
derive_more = "0.99.13"
pratt = "0.3.0"
proptest = "1.0.0"
test-strategy = "0.2.0"
readyset-util = { path = "../readyset-util" }
thiserror = "1.0.26"
hex = "0.4.3"
rust_decimal = { version = "1.26", features = ["db-tokio-postgres"] }
eui48 = { workspace = true }
uuid = { version = "0.8", features = ["v4"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
bit-vec = { version = "0.6", features = ["serde"] }
triomphe = "0.1"
lazy_static = "1.4"
nom_locate = "4.0.0"
fail = "0.5.0"
chrono = "0.4"

concrete-iter = { path = "../concrete-iter" }
failpoint-macros = { path = "../failpoint-macros" }

[dev-dependencies]
assert_approx_eq = "1.1.0"
pretty_assertions = "0.7.2"
bincode = "1.3"
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "analysis"
harness = false

[features]
debug = []
failure_injection = ["fail/failpoints"]
