[package]
name = "readyset-tracing"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive","env"] }
once_cell = "1.9.0"
opentelemetry = { version = "0.17", features = ["rt-tokio"] }
opentelemetry-jaeger = {version = "0.16.0", features = ["rt-tokio"]}
parking_lot = "0.12.0"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
tokio = "1.17.0"
tracing = "0.1.32"
tracing-opentelemetry = "0.17.2"
tracing-subscriber = { version = "0.3.9", features = ["env-filter", "json"] }
readyset-tracing-proc-macros = { path = "proc-macros" }

[dev-dependencies]
anyhow = "1.0.53"
tokio = { version = "1.16.1", features = ["rt-multi-thread", "macros"] }
tracing-attributes = "0.1.20"
