[package]
name = "readyset-tracing"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive","env"] }
once_cell = "1.9.0"
parking_lot = "0.12.0"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
tokio = { workspace = true, features = ["full"] }
lazy_static = "1.0"

tracing = "0.1.40"
opentelemetry = { version = "0.21.0" }
opentelemetry-otlp = { version = "0.14.0" }
opentelemetry-semantic-conventions = "0.13"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3.9", features = ["env-filter", "json"] }
tracing-appender = "0.2.3"
opentelemetry_sdk = { version = "0.21.2", features = ["rt-tokio"] }

[dev-dependencies]
tracing-attributes = "0.1.27"
